cli: append formated exception to unknown error messages
Exception.__str__ merely formats the exception arguments, but not its
type, which can be next to useless.

$ liquidctl -m smart set fan speed 90
ERROR: Unexpected error with NZXT Smart Device (V1): 'fan'

To fix, use traceback.format_exception instead.

$ liquidctl -m smart set fan speed 90
ERROR: Unexpected error with NZXT Smart Device (V1): KeyError: 'fan'

Fixes: 4ee1cb37b06a ("cli: improve error reporting and process all
devices before aborting")
Reported-by: u/nimbleping (on reddit)