error: Add dedicated NotSupportedByDevice|Driver errors
Related: #151/comment ("This controller doesn't support fan control or
report any (variable) status information.")