Fix invalid access to speed_channel_count
speed_channel_count is (currently) discarded after it is used to create
_speed_channels.  Thus, the code would fail with:

    AttributeError: 'Device' object has no attribute 'speed_channel_count'

This also fixes a bug that had been created in get_status, since it
enumerates _speed_channels.

While at this point we're pretty sure that all (physical) channels will
always have the same properties (i.e. smin, smax), I'm just not ready
yet to make this cleanup.  So until then,  _speed_channels should only
carry real channels.